/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.ui;

import inventory.Controller.CustomerController;
import inventory.Controller.InvoiceController;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sithara
 */
public class LoyaltyCards extends javax.swing.JFrame {

    /**
     * Creates new form LoyaltyCards
     */
    public static int POINT = 0;
    public static String CURRENTTOTAL = "";
    public static String CUSTOMERID = "";
    private String netTotal;
    private String invId;
    int once = 0;
    int once2 = 0;
    
    public LoyaltyCards() {
        initComponents();
        init();
        updateCustomerTable();
        setCustomerTableHeader();
    }
    
    public LoyaltyCards(String netTotal , String invId) {
        initComponents();
        init();
        updateCustomerTable();
        setCustomerTableHeader();
        this.netTotal = netTotal;
        invoiceTotalLbl.setText(netTotal); 
        this.invId = invId;
    }

    
    public void init() {
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        tableStyle(CustomerTable);
        
    }
    
    
    public void close() {
        WindowEvent windowClosingEvnt = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClosingEvnt);
    }

    public void setCustomerTableHeader() {
        TableColumn col = CustomerTable.getColumnModel().getColumn(0);
        col.setHeaderValue("Customer ID");
        col.setPreferredWidth(100);
        TableColumn col2 = CustomerTable.getColumnModel().getColumn(1);
        col2.setHeaderValue("Customer Name");
        col2.setPreferredWidth(100);
        TableColumn col3 = CustomerTable.getColumnModel().getColumn(2);
        col3.setHeaderValue("Loyalty Card No");
        col3.setPreferredWidth(100);
        TableColumn col4 = CustomerTable.getColumnModel().getColumn(3);
        col4.setHeaderValue("Points");
        col4.setPreferredWidth(100);
    }
    
    public void tableStyle(JTable table) {
        JTableHeader tableheader = table.getTableHeader();
        Color headerBlue = new Color(0, 102, 153);
        tableheader.setBackground(headerBlue);
        tableheader.setForeground(Color.WHITE);
        tableheader.setFont(new Font("Tahoma", Font.BOLD, 14));
        ((DefaultTableCellRenderer) tableheader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
    }
    
    public void updateCustomerTable(){
        try {
            ResultSet resultSet = CustomerController.getCustomer();
            CustomerTable.setModel(DbUtils.resultSetToTableModel(resultSet));
            setCustomerTableHeader();

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NicTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CardNoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        PayPointBtn = new javax.swing.JButton();
        payPointtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NewPointLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        invoiceTotalLbl = new javax.swing.JLabel();
        addPointLbl = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loyalty Cards");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(371, 371, 371))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel19))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer NIC");

        NicTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NicTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NicTxtKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Loyalty Card No");

        CardNoTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CardNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CardNoTxtKeyReleased(evt);
            }
        });

        CustomerTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CustomerTable.setShowHorizontalLines(false);
        CustomerTable.setShowVerticalLines(false);
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        PayPointBtn.setText("Pay Points");
        PayPointBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayPointBtnActionPerformed(evt);
            }
        });

        payPointtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Points");

        NewPointLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(" Added Points");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Invoice Total");

        invoiceTotalLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        invoiceTotalLbl.setText("000");

        addPointLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addPointLbl.setText("000");

        ResetBtn.setBackground(new java.awt.Color(0, 102, 153));
        ResetBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(invoiceTotalLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addPointLbl)
                                    .addComponent(NewPointLbl))))
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(payPointtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PayPointBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(NicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(CardNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ResetBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jLabel6)
                    .addContainerGap(721, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CardNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PayPointBtn)
                            .addComponent(payPointtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(invoiceTotalLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewPointLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPointLbl)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(464, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(21, 21, 21)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayPointBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayPointBtnActionPerformed
        // TODO add your handling code here:
        try{
        if(!payPointtxt.getText().equals("") ){
            
            if(once2 == 0){
                int row = CustomerTable.getSelectedRow(); //   Logger.getLogger(LoyaltyCards.class.getName()).log(Level.SEVERE, null, ex);
                String pnt = CustomerTable.getModel().getValueAt(row, 3).toString();
                float redu = Float.parseFloat(pnt) - Float.parseFloat(payPointtxt.getText());
                float reduceTotal = Float.parseFloat(netTotal) - Float.parseFloat(pnt);
                if(redu < 0){
                    JOptionPane.showMessageDialog(rootPane, "Not Enough Points");
                }
                CUSTOMERID = CustomerTable.getModel().getValueAt(row, 0).toString();
                CURRENTTOTAL = Float.toString(reduceTotal);
                JOptionPane.showMessageDialog(null, "Successfully Paid Points");
                updateCustomerTable();
                //       InvoiceController.updateTotalInotPoint(invId, Float.toString(reduceTotal));
                this.once2 = 1;
            }else{
                JOptionPane.showMessageDialog(rootPane, "Not allowed to add more than once");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "No Points value");
        }}catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Select the Custmer again");
        }
    }//GEN-LAST:event_PayPointBtnActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        // TODO add your handling code here:
        
        int row = CustomerTable.getSelectedRow();
        String customerId = CustomerTable.getModel().getValueAt(row, 0).toString();
        
         if(!customerId.equals("") && once == 0){
             try {
                 float totalFloat = Float.parseFloat(netTotal);
                 int tot = Math.round(totalFloat);
                 int addedpoint = tot / 1000;
                 addPointLbl.setText(Integer.toString(addedpoint));
                 float currpoint = InvoiceController.getCurrentPoint(customerId);
                 float newTotal = addedpoint + currpoint;
                 InvoiceController.addPoint(Float.toString(newTotal),customerId);
                 updateCustomerTable();
                 this.once = 1;
             } catch (ClassNotFoundException | SQLException ex) {
                 Logger.getLogger(InvoiceFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
            }
    
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void NicTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NicTxtKeyReleased
        // TODO add your handling code here:
        String nic = NicTxt.getText();
        try {
            ResultSet resultSet = CustomerController.getInfoCustomerById(nic);
            CustomerTable.setModel(DbUtils.resultSetToTableModel(resultSet));
            setCustomerTableHeader();

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_NicTxtKeyReleased

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        updateCustomerTable();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void CardNoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CardNoTxtKeyReleased
        // TODO add your handling code here:
        String nic = CardNoTxt.getText();
        try {
            ResultSet resultSet = CustomerController.getInfoCustomerByCardNo(nic);
            CustomerTable.setModel(DbUtils.resultSetToTableModel(resultSet));
            setCustomerTableHeader();

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_CardNoTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoyaltyCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoyaltyCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoyaltyCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoyaltyCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoyaltyCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CardNoTxt;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JLabel NewPointLbl;
    private javax.swing.JTextField NicTxt;
    private javax.swing.JButton PayPointBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel addPointLbl;
    private javax.swing.JLabel invoiceTotalLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField payPointtxt;
    // End of variables declaration//GEN-END:variables
}
